In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/train.csv')
df.head()

,beds,baths,size,size_units,lot_size,lot_size_units,zip_code,price
0,3,2.5,2590.0,sqft,6000.00,sqft,98144,795000.0
1,4,2.0,2240.0,sqft,0.31,acre,98106,915000.0
2,4,3.0,2040.0,sqft,3783.00,sqft,98107,950000.0
3,4,3.0,3800.0,sqft,5175.00,sqft,98199,1950000.0
4,2,2.0,1042.0,sqft,NaN,NaN,98102,950000.0

In [3]:
df.describe()

,beds,baths,size,lot_size,zip_code,price
count,2016.000000,2016.000000,2016.000000,1669.000000,2016.000000,2.016000e+03
mean,2.857639,2.159970,1735.740575,3871.059694,98123.638889,9.636252e+05
std,1.255092,1.002023,920.132591,2719.402066,22.650819,9.440954e+05
min,1.000000,0.500000,250.000000,0.230000,98101.000000,1.590000e+05
25%,2.000000,1.500000,1068.750000,1252.000000,98108.000000,6.017500e+05
50%,3.000000,2.000000,1560.000000,4000.000000,98117.000000,8.000000e+05
75%,4.000000,2.500000,2222.500000,6000.000000,98126.000000,1.105250e+06
max,15.000000,9.000000,11010.000000,9998.000000,98199.000000,2.500000e+07

In [4]:
df.loc[:,['beds','baths','size','size_units','price']]

      beds  baths    size size_units      price
0        3    2.5  2590.0       sqft   795000.0
1        4    2.0  2240.0       sqft   915000.0
2        4    3.0  2040.0       sqft   950000.0
3        4    3.0  3800.0       sqft  1950000.0
4        2    2.0  1042.0       sqft   950000.0
...    ...    ...     ...        ...        ...
2011     3    2.0  1370.0       sqft   910000.0
2012     1    1.0   889.0       sqft   550000.0
2013     4    2.0  2140.0       sqft  1150000.0
2014     2    2.0   795.0       sqft   590000.0
2015     3    2.0  1710.0       sqft   659000.0

[2016 rows x 5 columns]

In [5]:
df.loc[df['beds'].between(3,4),['beds','baths','size','size_units','price']]

      beds  baths    size size_units      price
0        3    2.5  2590.0       sqft   795000.0
1        4    2.0  2240.0       sqft   915000.0
2        4    3.0  2040.0       sqft   950000.0
3        4    3.0  3800.0       sqft  1950000.0
8        3    2.5  1520.0       sqft   565000.0
...    ...    ...     ...        ...        ...
2008     3    2.0  1482.0       sqft   919000.0
2009     3    3.5  1680.0       sqft   675000.0
2011     3    2.0  1370.0       sqft   910000.0
2013     4    2.0  2140.0       sqft  1150000.0
2015     3    2.0  1710.0       sqft   659000.0

[1043 rows x 5 columns]

In [6]:
df.rename({'size_units':'units'} , axis = 'columns')

      beds  baths    size units  lot_size lot_size_units  zip_code      price
0        3    2.5  2590.0  sqft   6000.00           sqft     98144   795000.0
1        4    2.0  2240.0  sqft      0.31           acre     98106   915000.0
2        4    3.0  2040.0  sqft   3783.00           sqft     98107   950000.0
3        4    3.0  3800.0  sqft   5175.00           sqft     98199  1950000.0
4        2    2.0  1042.0  sqft       NaN            NaN     98102   950000.0
...    ...    ...     ...   ...       ...            ...       ...        ...
2011     3    2.0  1370.0  sqft      0.50           acre     98112   910000.0
2012     1    1.0   889.0  sqft       NaN            NaN     98121   550000.0
2013     4    2.0  2140.0  sqft   6250.00           sqft     98199  1150000.0
2014     2    2.0   795.0  sqft       NaN            NaN     98103   590000.0
2015     3    2.0  1710.0  sqft   4267.00           sqft     98133   659000.0

[2016 rows x 8 columns]